import {
    ClassicEditor,
    Essentials,
    Paragraph,
    Alignment,
    Bold,
    Italic,
    Heading,
    Link,
    LinkImage,
    AutoLink,
    List,
    BlockQuote,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Indent,
    IndentBlock,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    PasteFromOffice,
    Table,
    TableCellProperties,
    TableProperties,
    TableToolbar,
    MediaEmbed,
    SimpleUploadAdapter,
    Undo,
} from 'ckeditor5';
import 'ckeditor5/ckeditor5.css';

window.CKEditorClassic = ClassicEditor;
window.CKEditorConfig = {
    licenseKey: 'GPL',
    plugins: [
        Essentials,
        Paragraph,
        Alignment,
        Bold,
        Italic,
        Heading,
        Link,
        LinkImage,
        AutoLink,
        List,
        BlockQuote,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        GeneralHtmlSupport,
        Indent,
        IndentBlock,
        Image,
        ImageCaption,
        ImageInsert,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        PasteFromOffice,
        Table,
        TableCellProperties,
        TableProperties,
        TableToolbar,
        MediaEmbed,
        SimpleUploadAdapter,
        Undo,
    ],
    toolbar: [
        'heading',
        '|',
        'fontFamily',
        'fontSize',
        'fontColor',
        'fontBackgroundColor',
        '|',
        'bold',
        'italic',
        'link',
        'alignment',
        'outdent',
        'indent',
        'bulletedList',
        'numberedList',
        'blockQuote',
        'imageUpload',
        'insertTable',
        'mediaEmbed',
        'tableProperties',
        'tableCellProperties',
        '|',
        'undo',
        'redo',
    ],
    fontFamily: {
        supportAllValues: true,
    },
    fontSize: {
        options: [10, 12, 14, 'default', 18, 24, 32],
        supportAllValues: true,
    },
    htmlSupport: {
        allow: [
            {
                name: /^(h[1-6]|p|span|div|figure|figcaption|table|thead|tbody|tfoot|tr|th|td|colgroup|col|ul|ol|li|blockquote|a|img|iframe|strong|em|b|i|u|s|sub|sup|br)$/,
                attributes: {
                    class: true,
                    style: true,
                    href: true,
                    src: true,
                    alt: true,
                    title: true,
                    width: true,
                    height: true,
                    colspan: true,
                    rowspan: true,
                    target: true,
                    rel: true,
                    frameborder: true,
                    allow: true,
                    allowfullscreen: true,
                },
                styles: {
                    color: true,
                    'background-color': true,
                    'border-color': true,
                    'border-style': true,
                    'border-width': true,
                    'border-collapse': true,
                    'font-family': true,
                    'font-size': true,
                    'font-style': true,
                    'font-weight': true,
                    height: true,
                    'line-height': true,
                    margin: true,
                    'margin-left': true,
                    'margin-right': true,
                    padding: true,
                    'padding-left': true,
                    'text-align': true,
                    'text-decoration': true,
                    'vertical-align': true,
                    width: true,
                },
            },
        ],
        disallow: [
            {
                name: 'script',
            },
            {
                name: /[\s\S]+/,
                attributes: {
                    key: /^on/i,
                },
            },
            {
                name: /[\s\S]+/,
                styles: {
                    key: /^position$/i,
                },
            },
        ],
    },
    simpleUpload: {
        uploadUrl: '/guru/uploads/editor-image',
        headers: {
            'X-CSRF-TOKEN': document.querySelector('meta[name=csrf-token]')?.content || '',
            'Accept': 'application/json',
        },
    },
    table: {
        contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'],
    },
    image: {
        toolbar: [
            'imageTextAlternative',
            'toggleImageCaption',
            'linkImage',
            '|',
            'imageStyle:inline',
            'imageStyle:block',
            'imageStyle:side',
            '|',
            'resizeImage',
        ],
    },
};

window.dispatchEvent(new CustomEvent('ckeditor:ready'));
