import {
    ClassicEditor,
    Essentials,
    Paragraph,
    Bold,
    Italic,
    Heading,
    Link,
    AutoLink,
    List,
    BlockQuote,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Table,
    TableToolbar,
    MediaEmbed,
    SimpleUploadAdapter,
    Undo,
} from 'ckeditor5';
import 'ckeditor5/ckeditor5.css';

window.CKEditorClassic = ClassicEditor;
window.CKEditorConfig = {
    licenseKey: 'GPL',
    plugins: [
        Essentials,
        Paragraph,
        Bold,
        Italic,
        Heading,
        Link,
        AutoLink,
        List,
        BlockQuote,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        Table,
        TableToolbar,
        MediaEmbed,
        SimpleUploadAdapter,
        Undo,
    ],
    toolbar: [
        'heading',
        '|',
        'bold',
        'italic',
        'link',
        'bulletedList',
        'numberedList',
        'blockQuote',
        'uploadImage',
        'insertTable',
        'mediaEmbed',
        '|',
        'undo',
        'redo',
    ],
    table: {
        contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
    },
    image: {
        toolbar: [
            'imageTextAlternative',
            'toggleImageCaption',
            '|',
            'imageStyle:inline',
            'imageStyle:block',
            'imageStyle:side',
            '|',
            'resizeImage',
        ],
    },
};

window.dispatchEvent(new CustomEvent('ckeditor:ready'));
